


# broj = 1848  #int
# dec = 5.21889848


# skola = "hvuihgvurgv"

# sk = 'vbudbvubvuf'



# True 
# False



# print("cygvgdvuydvgyu")


# broj = 17


# print(broj)

# 4785byfyfybg

# eygur tybgytbg 


# broj-neki 

# ------------------------------


# ime = str(input("Unesite neko ime: "))

# ime = 818848

# print(ime)


# godine = int(input("Unesite vase g/odine: "))


# -----


# ime = str(input("Unesite Vase ime: "))

# godine = int(input("Unesite Vase godine: "))


# # Ja se zovem -----, i imam -- godina


# print("Ja se zovem", ime , "i imam", godine , "godina")

# print("Ja se zovem " + ime) 



# -------------------




# Ja sam iz ---------- i idem u ------- skolu.


# grad = str(input("Unesite ime vase grada: "))

# skola = str(input("Unesite ime vaseg skola " ))

# print("Ja sam iz" , grad, "i idem u ", skola)



# ------------------------------------------



# +-*/


# broj1 = 10
# broj2 = 20

# print(broj1 - broj2)
# print(broj1 + broj2)
# print(broj1 * broj2)
# print(broj1 / broj2)


# 5 % 2 = 1
# 5 // 2 = 2


# --------------------------------

# 5 => 5.0

# a 

# stranica_kocke_a = float(input("Unesite stranicu kocke: "))

# zapremina = stranica_kocke_a ** 3

# print("Zapremina kocke je: ", stranica_kocke_a ** 3)


# print(5**)




# myset = {"apple", "banana", 1,"apple",True,4.5}
# tropical = {"pineapple", "mango", "papaya"}
# myset.update(tropical)
# print(myset)
# myset.add("cherry")
# print(myset)
# tropical = {"pineapple", "mango", "papaya"}
# tropical.remove("mango")
# print(tropical)
# tropical = {"pineapple", "mango", "papaya"}
# tropical.discard("mango")
# print(tropical)
# tropical.pop()
# print(tropical)tropical = {"pineapple", "mango", "papaya"}
# tropical = {"pineapple", "mango", "papaya"}
# tropical.clear()
# print(tropical)
# tropical = {"pineapple", "mango", "papaya"}
# for i in tropical:
#     print(i)
# myset = {"apple", "banana", 1,"apple",True,4.5}
# tropical = {"pineapple", "mango", "papaya"}
# noviset=myset.union(tropical)
# print(noviset)
# x = {"apple", "banana", "cherry"}
# y = {"google", "microsoft", "apple"}

# noviset=x.intersection_update(y)

# print(x)
# x = {"apple", "banana", "cherry"}
# y = {"google", "microsoft", "apple"}

# x.symmetric_difference_update(y)

# print(x)
# Write a Python program to find maximum and the minimum value in a set
#github.com/saracevicsara