


# broj = 1848  #int
# dec = 5.21889848


# skola = "hvuihgvurgv"

# sk = 'vbudbvubvuf'



# True 
# False



# print("cygvgdvuydvgyu")


# broj = 17


# print(broj)

# 4785byfyfybg

# eygur tybgytbg 


# broj-neki 

# ------------------------------


# ime = str(input("Unesite neko ime: "))

# ime = 818848

# print(ime)


# godine = int(input("Unesite vase g/odine: "))


# -----


# ime = str(input("Unesite Vase ime: "))

# godine = int(input("Unesite Vase godine: "))


# # Ja se zovem -----, i imam -- godina


# print("Ja se zovem", ime , "i imam", godine , "godina")

# print("Ja se zovem " + ime) 



# -------------------




# Ja sam iz ---------- i idem u ------- skolu.


# grad = str(input("Unesite ime vase grada: "))

# skola = str(input("Unesite ime vaseg skola " ))

# print("Ja sam iz" , grad, "i idem u ", skola)



# ------------------------------------------



# +-*/


# broj1 = 10
# broj2 = 20

# print(broj1 - broj2)
# print(broj1 + broj2)
# print(broj1 * broj2)
# print(broj1 / broj2)


# 5 % 2 = 1
# 5 // 2 = 2


# --------------------------------

# 5 => 5.0

# a 

# stranica_kocke_a = float(input("Unesite stranicu kocke: "))

# zapremina = stranica_kocke_a ** 3

# print("Zapremina kocke je: ", stranica_kocke_a ** 3)


# print(5**)
